name: Deploy to ALT Linux Space Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: als-tiny
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare static site
        run: |
          mkdir _site
          find . -mindepth 1 -maxdepth 1 \
            ! -name '.git' \
            ! -name '.forgejo' \
            ! -name '_site' \
            -exec cp -a {} _site/ \;

      - name: Deploy static site
        uses: actions/deploy-pages@v1
        with:
          directory: ./_site
          custom-domain: pirao.bdpsy.ru
